version: '3'

services:
  drone-server:
    image: drone/drone:0.8.0
    ports:
      - 80:8000
    volumes:
      - ./drone:/var/lib/drone/
    restart: always
    environment:
        - DRONE_OPEN=true
           - DRONE_ORGS=dolores,dogpatch
           - DRONE_ADMIN=johnsmith,janedoe
           - DRONE_HOST=${DRONE_HOST}
           - DRONE_GITHUB=true
           - DRONE_GITHUB_CLIENT=${DRONE_GITHUB_CLIENT}
           - DRONE_GITHUB_SECRET=${DRONE_GITHUB_SECRET}
           - DRONE_SECRET=${DRONE_SECRET}

  drone-agent:
    image: drone/drone:0.8.0
    command: agent
    restart: always
    depends_on: [ drone-server ]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DRONE_SERVER=drone-server:9000
            - DRONE_DEBUG=true
            - DRONE_SECRET=${DRONE_SECRET}